### Numpy Meshgrid

In [2]:
x = np.arange(-5, 5, 1)
y = np.arange(-5, 5, 1)
xx, yy = np.meshgrid(x, y, sparse=True)
print(xx)
print(yy)

[[-5 -4 -3 -2 -1  0  1  2  3  4]]
[[-5]
 [-4]
 [-3]
 [-2]
 [-1]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]]


### Numpy tile

In [3]:
a = np.array([0, 1, 2])
np.tile(a, 2)


array([0, 1, 2, 0, 1, 2])

In [4]:
np.tile(a, (2, 2))


array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [5]:
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [12]:
a = np.array([0, 1, 2])
b = np.array([0, 1, 2])
a = a.reshape(-1,1)
b = b.reshape(-1,1)
boxes = np.concatenate((a,b),axis = 1)
print(boxes)
boxes = np.tile(boxes,(1,2))
boxes

[[0 0]
 [1 1]
 [2 2]]


array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])